version: '3.9'

services:
  mysql:
    container_name: aular_db
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db_aular
      MYSQL_ROOT_PASSWORD: feijuca

#  app:
#    container_name: aular_api
#    build: .
#    restart: always
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mysql