version: '3.9'

services:
  mysql:
    container_name: aular_db
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db_aular
      MYSQL_ROOT_PASSWORD: feijuca